"""empty message

Revision ID: 633b16a517eb
Revises: 72c7bf7d6311
Create Date: 2025-08-07 10:28:45.850443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '633b16a517eb'
down_revision = '72c7bf7d6311'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('source', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('studios', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('release_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_episodes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_record', schema=None) as batch_op:
        batch_op.drop_column('total_episodes')
        batch_op.drop_column('release_year')
        batch_op.drop_column('studios')
        batch_op.drop_column('source')
        batch_op.drop_column('tags')

    # ### end Alembic commands ###
