"""Add synopsis column to MasterRecord

Revision ID: 72c7bf7d6311
Revises: 29d6d0d6098f
Create Date: 2025-08-06 21:26:05.971966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72c7bf7d6311'
down_revision = '29d6d0d6098f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('synopsis', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_record', schema=None) as batch_op:
        batch_op.drop_column('synopsis')

    # ### end Alembic commands ###
