"""add themes and rich filters

Revision ID: 843479bef60c
Revises: da8f1a560043
Create Date: 2025-08-08 13:08:26.649104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '843479bef60c'
down_revision = 'da8f1a560043'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('themes', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_record', schema=None) as batch_op:
        batch_op.drop_column('themes')

    # ### end Alembic commands ###
