"""Add user_score and scored_by columns

Revision ID: 9d1b60fcd243
Revises: b34a3eed6416
Create Date: 2025-08-07 15:17:42.876074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d1b60fcd243'
down_revision = 'b34a3eed6416'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scored_by', sa.Integer(), nullable=True))

    with op.batch_alter_table('user_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_score', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_list', schema=None) as batch_op:
        batch_op.drop_column('user_score')

    with op.batch_alter_table('master_record', schema=None) as batch_op:
        batch_op.drop_column('scored_by')

    # ### end Alembic commands ###
