"""Add rich Jikan fields to MasterRecord

Revision ID: b34a3eed6416
Revises: 633b16a517eb
Create Date: 2025-08-07 13:51:23.858496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b34a3eed6416'
down_revision = '633b16a517eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mal_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('mal_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('popularity', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint("uq_master_record_mal_id", ['mal_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_record', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('popularity')
        batch_op.drop_column('score')
        batch_op.drop_column('mal_type')
        batch_op.drop_column('mal_id')

    # ### end Alembic commands ###
