"""add rich fields to MasterRecord

Revision ID: da8f1a560043
Revises: 9d1b60fcd243
Create Date: 2025-08-08 12:36:39.441213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da8f1a560043'
down_revision = '9d1b60fcd243'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('aired_from', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('aired_to', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('demographics', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('members', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('favorites', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('relations', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('licensors', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('producers', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_record', schema=None) as batch_op:
        batch_op.drop_column('producers')
        batch_op.drop_column('licensors')
        batch_op.drop_column('relations')
        batch_op.drop_column('favorites')
        batch_op.drop_column('members')
        batch_op.drop_column('rating')
        batch_op.drop_column('demographics')
        batch_op.drop_column('duration')
        batch_op.drop_column('aired_to')
        batch_op.drop_column('aired_from')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
